import SideMenu from '@/components/sidebar/SideMenu'
import Sidebar from '@/components/sidebar/Sidebar'
import { cn } from '@/lib/utils'
import '@/styles/globals.css'
import { url } from 'inspector'
import { Poppins } from 'next/font/google'

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700'],
})

export const metadata = {
  title: 'Language Translation Assistant',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={cn(`${poppins.className} bg-[#1A1B1E]`)}>
        <div className='flex'>
          <Sidebar />
          <SideMenu />
          <div
            style={{
              backgroundImage: `url('/assets/background_image.png')`,
              backgroundRepeat: 'no-repeat',
              objectFit: 'cover',
              backdropFilter: 'blur(10px)',
            }}
            className='w-full p-8'
          >
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
