import Sidebar from '@/components/sidebar/Sidebar'
import SidebarProvider from '@/context/SidebarContext'
import { cn } from '@/lib/utils'
import '@/styles/globals.css'
import { Poppins, Inter } from 'next/font/google'

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700'],
})

//eslint-disable-next-line
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700'],
})

export const metadata = {
  title: 'Language Translation Assistant',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={cn(`${poppins.className} bg-[#1A1B1E]`)}>
        <div className='flex'>
          <SidebarProvider>
            <Sidebar />
            {children}
          </SidebarProvider>
        </div>
      </body>
    </html>
  )
}
